#!/usr/bin/env python3
"""Render the PR1 private-compute Supabase migration from the frozen PR0 contract."""

from __future__ import annotations

import argparse
from datetime import date, datetime
import json
from pathlib import Path
import sys
from typing import Any

from sqlalchemy import Date, DateTime, Integer

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.generate_pr0_schema_inventory import (  # noqa: E402
    DEFAULT_OUTPUT as INVENTORY_PATH,
    JSON_FIELD_CONTRACTS,
)
from src.storage import Base  # noqa: E402


LEGACY_ONLY_TABLES = {"schema_migrations"}
SYMBOL_COLUMNS = {
    "analysis_history.code",
    "backtest_results.code",
    "backtest_summaries.code",
    "decision_signals.stock_code",
    "fundamental_snapshot.code",
    "llm_usage.stock_code",
    "news_intel.code",
    "portfolio_corporate_actions.symbol",
    "portfolio_position_lots.symbol",
    "portfolio_positions.symbol",
    "portfolio_trades.symbol",
    "settlement_alert_states.symbol",
    "stock_daily.code",
}
CURRENCY_COLUMNS = {
    "portfolio_accounts.base_currency",
    "portfolio_cash_ledger.currency",
    "portfolio_corporate_actions.currency",
    "portfolio_daily_snapshots.base_currency",
    "portfolio_fx_rates.from_currency",
    "portfolio_fx_rates.to_currency",
    "portfolio_position_lots.currency",
    "portfolio_positions.currency",
    "portfolio_positions.valuation_currency",
    "portfolio_trades.currency",
}
NONNEGATIVE_EXACT_COLUMNS = {
    "attempt",
    "estimated_tokens",
    "latency_ms",
    "message_count",
    "quantity",
    "remaining_quantity",
    "sellable_quantity",
    "source_message_count",
    "total_quantity",
    "unsettled_quantity",
}


def _quote_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (date, datetime)):
        return f"'{value.isoformat()}'"
    return "'" + str(value).replace("'", "''") + "'"


def _column_default(table_name: str, column: Any) -> str | None:
    json_contract = JSON_FIELD_CONTRACTS.get(f"{table_name}.{column.name}")
    if json_contract and not column.nullable:
        return f"'{json_contract['empty']}'::jsonb"
    default = column.default
    if default is None or default.is_sequence:
        return None
    if default.is_callable:
        return "now()" if _is_datetime_type(column.type) else None
    return _quote_literal(default.arg)


def _is_datetime_type(column_type: Any) -> bool:
    """Recognize direct and TypeDecorator-wrapped SQLAlchemy datetimes."""
    return isinstance(column_type, DateTime) or isinstance(
        getattr(column_type, "impl", None),
        DateTime,
    )


def _column_type(table_name: str, column: Any) -> str:
    if f"{table_name}.{column.name}" in JSON_FIELD_CONTRACTS:
        return "jsonb"
    if _is_datetime_type(column.type):
        return "timestamptz"
    if isinstance(column.type, Date):
        return "date"
    if isinstance(column.type, Integer):
        if column.primary_key or column.foreign_keys:
            return "bigint"
        return "integer"

    rendered = str(column.type).lower()
    if rendered == "float":
        return "double precision"
    return rendered


def _column_sql(table_name: str, column: Any) -> str:
    pieces = [column.name, _column_type(table_name, column)]
    if column.primary_key and isinstance(column.type, Integer) and not column.foreign_keys:
        pieces.append("generated by default as identity")
    if column.primary_key:
        pieces.append("primary key")
    elif not column.nullable:
        pieces.append("not null")

    default = _column_default(table_name, column)
    if default is not None:
        pieces.extend(("default", default))

    foreign_keys = list(column.foreign_keys)
    if foreign_keys:
        foreign_key = foreign_keys[0]
        target_table, target_column = foreign_key.target_fullname.split(".", 1)
        pieces.extend(("references", f"dsa.{target_table}({target_column})"))
        if foreign_key.ondelete:
            pieces.extend(("on delete", foreign_key.ondelete.lower()))
    return " ".join(pieces)


def _check_constraints(table_name: str, columns: list[Any]) -> list[str]:
    checks: list[str] = []
    for column in columns:
        qualified = f"{table_name}.{column.name}"
        nullable_guard = f"{column.name} is null or " if column.nullable else ""
        if qualified in SYMBOL_COLUMNS:
            checks.append(
                f"constraint ck_{table_name}_{column.name}_vn "
                f"check ({nullable_guard}{column.name} ~ '^[A-Z0-9]{{1,12}}[.]VN$')"
            )
        if qualified in CURRENCY_COLUMNS:
            checks.append(
                f"constraint ck_{table_name}_{column.name}_vnd "
                f"check ({nullable_guard}{column.name} = 'VND')"
            )
        if (
            column.name in NONNEGATIVE_EXACT_COLUMNS
            or column.name.endswith("_count")
            or column.name.endswith("_tokens")
        ):
            checks.append(
                f"constraint ck_{table_name}_{column.name}_nonnegative "
                f"check ({nullable_guard}{column.name} >= 0)"
            )
    return checks


def _render_table(table: Any) -> str:
    definitions = [_column_sql(table.name, column) for column in table.columns]
    for constraint in sorted(
        table.constraints,
        key=lambda item: (item.__class__.__name__, item.name or ""),
    ):
        if constraint.__class__.__name__ != "UniqueConstraint":
            continue
        columns = ", ".join(column.name for column in constraint.columns)
        definitions.append(f"constraint {constraint.name} unique ({columns})")
    definitions.extend(_check_constraints(table.name, list(table.columns)))
    body = ",\n  ".join(definitions)
    return f"create table dsa.{table.name} (\n  {body}\n);"


def _render_indexes(table: Any) -> list[str]:
    statements = []
    for index in sorted(table.indexes, key=lambda item: item.name or ""):
        unique = "unique " if index.unique else ""
        columns = ", ".join(column.name for column in index.columns)
        statements.append(
            f"create {unique}index {index.name} on dsa.{table.name} ({columns});"
        )
    return statements


def _worker_role_sql() -> str:
    return """do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'dsa_worker') then
    create role dsa_worker login noinherit nobypassrls;
  end if;
end
$$;

alter role dsa_worker login noinherit nobypassrls;
comment on role dsa_worker is
  'Routine daily-stock worker. Set its password only through protected operations.';"""


def render_migration() -> str:
    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))
    expected_tables = set(inventory["tables"]) - LEGACY_ONLY_TABLES
    metadata_tables = {
        table.name: table
        for table in Base.metadata.sorted_tables
        if table.name not in LEGACY_ONLY_TABLES
    }
    if set(metadata_tables) != expected_tables:
        raise RuntimeError("PR0 inventory and SQLAlchemy metadata table sets differ")

    sections = [
        "-- Generated by scripts/generate_pr1_supabase_migration.py.",
        "-- Runtime code is unchanged in PR1; schema_migrations remains SQLite-import only.",
        "",
        _worker_role_sql(),
        "",
        "create schema dsa;",
        "comment on schema dsa is 'Private compute data owned by daily_stock_analysis.';",
        "revoke all on schema dsa from public, anon, authenticated, service_role;",
        "",
    ]

    for table in Base.metadata.sorted_tables:
        if table.name in LEGACY_ONLY_TABLES:
            continue
        sections.extend((_render_table(table), ""))
        sections.extend(_render_indexes(table))
        sections.append("")

    sections.extend(
        (
            "revoke all on all tables in schema dsa "
            "from public, anon, authenticated, service_role;",
            "revoke all on all sequences in schema dsa "
            "from public, anon, authenticated, service_role;",
            "grant usage on schema dsa to dsa_worker;",
            "grant select, insert, update, delete on all tables in schema dsa to dsa_worker;",
            "grant usage, select on all sequences in schema dsa to dsa_worker;",
            "",
            "alter default privileges in schema dsa "
            "revoke all on tables from public, anon, authenticated, service_role;",
            "alter default privileges in schema dsa "
            "revoke all on sequences from public, anon, authenticated, service_role;",
            "alter default privileges in schema dsa "
            "grant select, insert, update, delete on tables to dsa_worker;",
            "alter default privileges in schema dsa "
            "grant usage, select on sequences to dsa_worker;",
            "",
        )
    )

    for table_name in sorted(expected_tables):
        sections.extend(
            (
                f"alter table dsa.{table_name} enable row level security;",
                f"create policy {table_name}_worker_all on dsa.{table_name}",
                "  for all",
                "  to dsa_worker",
                "  using (true)",
                "  with check (true);",
                "",
            )
        )
    return "\n".join(sections).rstrip() + "\n"


def _find_migration() -> Path:
    migrations = sorted(
        (ROOT / "supabase" / "migrations").glob("*_create_private_dsa_schema.sql")
    )
    if len(migrations) != 1:
        raise RuntimeError(
            "Expected exactly one CLI-generated *_create_private_dsa_schema.sql migration"
        )
    return migrations[0]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    output = (args.output or _find_migration()).resolve()
    rendered = render_migration()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != rendered:
            print(f"PR1 Supabase migration is stale: {output}")
            return 1
        print(f"PR1 Supabase migration is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote PR1 Supabase migration: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
