-- Generated by scripts/generate_pr1_supabase_migration.py.
-- Runtime code is unchanged in PR1; schema_migrations remains SQLite-import only.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'dsa_worker') then
    create role dsa_worker login noinherit nobypassrls;
  end if;
end
$$;

alter role dsa_worker login noinherit nobypassrls;
comment on role dsa_worker is
  'Routine daily-stock worker. Set its password only through protected operations.';

create schema dsa;
comment on schema dsa is 'Private compute data owned by daily_stock_analysis.';
revoke all on schema dsa from public, anon, authenticated, service_role;

create table dsa.agent_provider_turns (
  id bigint generated by default as identity primary key,
  session_id varchar(100) not null,
  run_id varchar(64) not null,
  provider varchar(64) not null,
  model varchar(160) not null,
  anchor_user_message_id integer not null,
  anchor_assistant_message_id integer not null,
  messages_json jsonb not null default '[]'::jsonb,
  contains_reasoning boolean not null default false,
  contains_tool_calls boolean not null default false,
  contains_thinking_blocks boolean not null default false,
  must_roundtrip boolean not null default false,
  estimated_tokens integer not null default 0,
  created_at timestamptz default now(),
  constraint ck_agent_provider_turns_estimated_tokens_nonnegative check (estimated_tokens >= 0)
);

create index ix_agent_provider_turn_bucket on dsa.agent_provider_turns (session_id, provider, model, must_roundtrip);
create index ix_agent_provider_turns_anchor_assistant_message_id on dsa.agent_provider_turns (anchor_assistant_message_id);
create index ix_agent_provider_turns_anchor_user_message_id on dsa.agent_provider_turns (anchor_user_message_id);
create index ix_agent_provider_turns_created_at on dsa.agent_provider_turns (created_at);
create index ix_agent_provider_turns_model on dsa.agent_provider_turns (model);
create index ix_agent_provider_turns_must_roundtrip on dsa.agent_provider_turns (must_roundtrip);
create index ix_agent_provider_turns_provider on dsa.agent_provider_turns (provider);
create index ix_agent_provider_turns_run_id on dsa.agent_provider_turns (run_id);
create index ix_agent_provider_turns_session_id on dsa.agent_provider_turns (session_id);

create table dsa.alert_cooldowns (
  id bigint generated by default as identity primary key,
  rule_id integer,
  rule_key varchar(255),
  target varchar(64) not null,
  severity varchar(16) not null default 'warning',
  last_triggered_at timestamptz,
  cooldown_until timestamptz,
  reason text,
  state varchar(16) not null default 'active',
  updated_at timestamptz default now(),
  constraint uix_alert_cooldown_rule_target_severity unique (rule_id, target, severity)
);

create index ix_alert_cooldowns_cooldown_until on dsa.alert_cooldowns (cooldown_until);
create index ix_alert_cooldowns_last_triggered_at on dsa.alert_cooldowns (last_triggered_at);
create index ix_alert_cooldowns_rule_id on dsa.alert_cooldowns (rule_id);
create index ix_alert_cooldowns_rule_key on dsa.alert_cooldowns (rule_key);
create index ix_alert_cooldowns_severity on dsa.alert_cooldowns (severity);
create index ix_alert_cooldowns_state on dsa.alert_cooldowns (state);
create index ix_alert_cooldowns_target on dsa.alert_cooldowns (target);
create index ix_alert_cooldowns_updated_at on dsa.alert_cooldowns (updated_at);

create table dsa.alert_notifications (
  id bigint generated by default as identity primary key,
  trigger_id integer,
  channel varchar(32) not null,
  attempt integer not null default 1,
  success boolean not null default false,
  error_code varchar(64),
  retryable boolean not null default false,
  latency_ms integer,
  diagnostics jsonb,
  created_at timestamptz default now(),
  constraint ck_alert_notifications_attempt_nonnegative check (attempt >= 0),
  constraint ck_alert_notifications_latency_ms_nonnegative check (latency_ms is null or latency_ms >= 0)
);

create index ix_alert_notification_trigger_channel on dsa.alert_notifications (trigger_id, channel);
create index ix_alert_notifications_channel on dsa.alert_notifications (channel);
create index ix_alert_notifications_created_at on dsa.alert_notifications (created_at);
create index ix_alert_notifications_success on dsa.alert_notifications (success);
create index ix_alert_notifications_trigger_id on dsa.alert_notifications (trigger_id);

create table dsa.alert_rules (
  id bigint generated by default as identity primary key,
  name varchar(64) not null,
  target_scope varchar(32) not null default 'single_symbol',
  target varchar(64) not null,
  alert_type varchar(32) not null,
  parameters jsonb not null default '{}'::jsonb,
  severity varchar(16) not null default 'warning',
  enabled boolean not null default true,
  source varchar(16) not null default 'api',
  cooldown_policy jsonb,
  notification_policy jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index ix_alert_rule_type_target on dsa.alert_rules (alert_type, target);
create index ix_alert_rules_alert_type on dsa.alert_rules (alert_type);
create index ix_alert_rules_created_at on dsa.alert_rules (created_at);
create index ix_alert_rules_enabled on dsa.alert_rules (enabled);
create index ix_alert_rules_severity on dsa.alert_rules (severity);
create index ix_alert_rules_source on dsa.alert_rules (source);
create index ix_alert_rules_target on dsa.alert_rules (target);
create index ix_alert_rules_target_scope on dsa.alert_rules (target_scope);
create index ix_alert_rules_updated_at on dsa.alert_rules (updated_at);

create table dsa.alert_triggers (
  id bigint generated by default as identity primary key,
  rule_id integer,
  target varchar(64) not null,
  observed_value double precision,
  threshold double precision,
  reason text,
  data_source varchar(64),
  data_timestamp timestamptz,
  triggered_at timestamptz default now(),
  status varchar(16) not null default 'triggered',
  diagnostics jsonb
);

create index ix_alert_trigger_rule_time on dsa.alert_triggers (rule_id, triggered_at);
create index ix_alert_triggers_data_timestamp on dsa.alert_triggers (data_timestamp);
create index ix_alert_triggers_rule_id on dsa.alert_triggers (rule_id);
create index ix_alert_triggers_status on dsa.alert_triggers (status);
create index ix_alert_triggers_target on dsa.alert_triggers (target);
create index ix_alert_triggers_triggered_at on dsa.alert_triggers (triggered_at);

create table dsa.analysis_history (
  id bigint generated by default as identity primary key,
  query_id varchar(64),
  code varchar(10) not null,
  name varchar(50),
  report_type varchar(16),
  sentiment_score integer,
  operation_advice varchar(20),
  trend_prediction varchar(50),
  analysis_summary text,
  raw_result jsonb,
  news_content text,
  context_snapshot jsonb,
  ideal_buy double precision,
  secondary_buy double precision,
  stop_loss double precision,
  take_profit double precision,
  created_at timestamptz default now(),
  constraint ck_analysis_history_code_vn check (code ~ '^[A-Z0-9]{1,12}[.]VN$')
);

create index ix_analysis_code_time on dsa.analysis_history (code, created_at);
create index ix_analysis_history_code on dsa.analysis_history (code);
create index ix_analysis_history_created_at on dsa.analysis_history (created_at);
create index ix_analysis_history_query_id on dsa.analysis_history (query_id);
create index ix_analysis_history_report_type on dsa.analysis_history (report_type);

create table dsa.backtest_summaries (
  id bigint generated by default as identity primary key,
  scope varchar(16) not null,
  code varchar(16),
  eval_window_days integer not null default 10,
  engine_version varchar(16) not null default 'v1',
  computed_at timestamptz default now(),
  total_evaluations integer default 0,
  completed_count integer default 0,
  insufficient_count integer default 0,
  long_count integer default 0,
  cash_count integer default 0,
  win_count integer default 0,
  loss_count integer default 0,
  neutral_count integer default 0,
  direction_accuracy_pct double precision,
  win_rate_pct double precision,
  neutral_rate_pct double precision,
  avg_stock_return_pct double precision,
  avg_simulated_return_pct double precision,
  stop_loss_trigger_rate double precision,
  take_profit_trigger_rate double precision,
  ambiguous_rate double precision,
  avg_days_to_first_hit double precision,
  advice_breakdown_json jsonb,
  diagnostics_json jsonb,
  constraint uix_backtest_summary_scope_code_window_version unique (scope, code, eval_window_days, engine_version),
  constraint ck_backtest_summaries_code_vn check (code is null or code ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_backtest_summaries_completed_count_nonnegative check (completed_count is null or completed_count >= 0),
  constraint ck_backtest_summaries_insufficient_count_nonnegative check (insufficient_count is null or insufficient_count >= 0),
  constraint ck_backtest_summaries_long_count_nonnegative check (long_count is null or long_count >= 0),
  constraint ck_backtest_summaries_cash_count_nonnegative check (cash_count is null or cash_count >= 0),
  constraint ck_backtest_summaries_win_count_nonnegative check (win_count is null or win_count >= 0),
  constraint ck_backtest_summaries_loss_count_nonnegative check (loss_count is null or loss_count >= 0),
  constraint ck_backtest_summaries_neutral_count_nonnegative check (neutral_count is null or neutral_count >= 0)
);

create index ix_backtest_summaries_code on dsa.backtest_summaries (code);
create index ix_backtest_summaries_computed_at on dsa.backtest_summaries (computed_at);
create index ix_backtest_summaries_scope on dsa.backtest_summaries (scope);

create table dsa.conversation_messages (
  id bigint generated by default as identity primary key,
  session_id varchar(100) not null,
  role varchar(20) not null,
  content text not null,
  created_at timestamptz default now()
);

create index ix_conversation_messages_created_at on dsa.conversation_messages (created_at);
create index ix_conversation_messages_session_id on dsa.conversation_messages (session_id);

create table dsa.conversation_summaries (
  id bigint generated by default as identity primary key,
  session_id varchar(100) not null,
  summary text not null,
  covered_message_id integer not null default 0,
  source_message_count integer not null default 0,
  estimated_tokens integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint ck_conversation_summaries_source_message_count_nonnegative check (source_message_count >= 0),
  constraint ck_conversation_summaries_estimated_tokens_nonnegative check (estimated_tokens >= 0)
);

create index ix_conversation_summaries_created_at on dsa.conversation_summaries (created_at);
create unique index ix_conversation_summaries_session_id on dsa.conversation_summaries (session_id);
create index ix_conversation_summaries_updated_at on dsa.conversation_summaries (updated_at);

create table dsa.decision_signal_feedback (
  id bigint generated by default as identity primary key,
  signal_id integer not null,
  feedback_value varchar(16) not null,
  reason_code varchar(64),
  note text,
  source varchar(16) not null default 'api',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index ix_decision_signal_feedback_created_at on dsa.decision_signal_feedback (created_at);
create index ix_decision_signal_feedback_feedback_value on dsa.decision_signal_feedback (feedback_value);
create index ix_decision_signal_feedback_reason_code on dsa.decision_signal_feedback (reason_code);
create unique index ix_decision_signal_feedback_signal_id on dsa.decision_signal_feedback (signal_id);
create index ix_decision_signal_feedback_source on dsa.decision_signal_feedback (source);
create index ix_decision_signal_feedback_updated_at on dsa.decision_signal_feedback (updated_at);

create table dsa.decision_signal_outcomes (
  id bigint generated by default as identity primary key,
  signal_id integer not null,
  horizon varchar(16) not null,
  engine_version varchar(32) not null,
  eval_status varchar(24) not null default 'unable',
  outcome varchar(16),
  direction_expected varchar(16),
  direction_correct boolean,
  unable_reason varchar(64),
  anchor_date date,
  eval_window_days integer,
  start_price double precision,
  end_close double precision,
  max_high double precision,
  min_low double precision,
  stock_return_pct double precision,
  action varchar(16),
  market varchar(8),
  market_phase varchar(24),
  source_type varchar(32),
  source_agent varchar(64),
  plan_quality varchar(16),
  data_quality_level varchar(24),
  holding_state varchar(16) not null default 'unknown',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint uix_decision_signal_outcome_key unique (signal_id, horizon, engine_version)
);

create index ix_decision_signal_outcome_stats_action on dsa.decision_signal_outcomes (engine_version, action, horizon);
create index ix_decision_signal_outcome_stats_market on dsa.decision_signal_outcomes (engine_version, market, horizon);
create index ix_decision_signal_outcomes_action on dsa.decision_signal_outcomes (action);
create index ix_decision_signal_outcomes_anchor_date on dsa.decision_signal_outcomes (anchor_date);
create index ix_decision_signal_outcomes_created_at on dsa.decision_signal_outcomes (created_at);
create index ix_decision_signal_outcomes_data_quality_level on dsa.decision_signal_outcomes (data_quality_level);
create index ix_decision_signal_outcomes_direction_expected on dsa.decision_signal_outcomes (direction_expected);
create index ix_decision_signal_outcomes_engine_version on dsa.decision_signal_outcomes (engine_version);
create index ix_decision_signal_outcomes_eval_status on dsa.decision_signal_outcomes (eval_status);
create index ix_decision_signal_outcomes_holding_state on dsa.decision_signal_outcomes (holding_state);
create index ix_decision_signal_outcomes_horizon on dsa.decision_signal_outcomes (horizon);
create index ix_decision_signal_outcomes_market on dsa.decision_signal_outcomes (market);
create index ix_decision_signal_outcomes_market_phase on dsa.decision_signal_outcomes (market_phase);
create index ix_decision_signal_outcomes_outcome on dsa.decision_signal_outcomes (outcome);
create index ix_decision_signal_outcomes_plan_quality on dsa.decision_signal_outcomes (plan_quality);
create index ix_decision_signal_outcomes_signal_id on dsa.decision_signal_outcomes (signal_id);
create index ix_decision_signal_outcomes_source_agent on dsa.decision_signal_outcomes (source_agent);
create index ix_decision_signal_outcomes_source_type on dsa.decision_signal_outcomes (source_type);
create index ix_decision_signal_outcomes_unable_reason on dsa.decision_signal_outcomes (unable_reason);
create index ix_decision_signal_outcomes_updated_at on dsa.decision_signal_outcomes (updated_at);

create table dsa.decision_signals (
  id bigint generated by default as identity primary key,
  stock_code varchar(16) not null,
  stock_name varchar(64),
  market varchar(8) not null,
  source_type varchar(32) not null,
  source_agent varchar(64),
  source_report_id integer,
  trace_id varchar(64),
  market_phase varchar(24),
  trigger_source varchar(64) not null,
  action varchar(16) not null,
  action_label varchar(32),
  confidence double precision,
  score integer,
  horizon varchar(16),
  entry_low double precision,
  entry_high double precision,
  stop_loss double precision,
  target_price double precision,
  invalidation text,
  watch_conditions text,
  reason text,
  risk_summary text,
  catalyst_summary text,
  evidence_json jsonb,
  data_quality_summary_json jsonb,
  plan_quality varchar(16) not null default 'unknown',
  status varchar(16) not null default 'active',
  expires_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  metadata_json jsonb,
  constraint ck_decision_signals_stock_code_vn check (stock_code ~ '^[A-Z0-9]{1,12}[.]VN$')
);

create index ix_decision_signal_market_status_time on dsa.decision_signals (market, status, created_at);
create index ix_decision_signal_report_type_market_stock_action_horizon_phase on dsa.decision_signals (source_report_id, source_type, market, stock_code, action, horizon, market_phase);
create index ix_decision_signal_stock_status_time on dsa.decision_signals (stock_code, status, created_at);
create index ix_decision_signal_trace_type_market_stock_action_horizon_phase on dsa.decision_signals (trace_id, source_type, market, stock_code, action, horizon, market_phase);
create index ix_decision_signals_action on dsa.decision_signals (action);
create index ix_decision_signals_created_at on dsa.decision_signals (created_at);
create index ix_decision_signals_expires_at on dsa.decision_signals (expires_at);
create index ix_decision_signals_horizon on dsa.decision_signals (horizon);
create index ix_decision_signals_market on dsa.decision_signals (market);
create index ix_decision_signals_market_phase on dsa.decision_signals (market_phase);
create index ix_decision_signals_plan_quality on dsa.decision_signals (plan_quality);
create index ix_decision_signals_source_report_id on dsa.decision_signals (source_report_id);
create index ix_decision_signals_source_type on dsa.decision_signals (source_type);
create index ix_decision_signals_status on dsa.decision_signals (status);
create index ix_decision_signals_stock_code on dsa.decision_signals (stock_code);
create index ix_decision_signals_trace_id on dsa.decision_signals (trace_id);
create index ix_decision_signals_trigger_source on dsa.decision_signals (trigger_source);
create index ix_decision_signals_updated_at on dsa.decision_signals (updated_at);

create table dsa.fundamental_snapshot (
  id bigint generated by default as identity primary key,
  query_id varchar(64) not null,
  code varchar(10) not null,
  payload jsonb not null default '{}'::jsonb,
  source_chain jsonb,
  coverage jsonb,
  created_at timestamptz default now(),
  constraint ck_fundamental_snapshot_code_vn check (code ~ '^[A-Z0-9]{1,12}[.]VN$')
);

create index ix_fundamental_snapshot_code on dsa.fundamental_snapshot (code);
create index ix_fundamental_snapshot_created on dsa.fundamental_snapshot (created_at);
create index ix_fundamental_snapshot_created_at on dsa.fundamental_snapshot (created_at);
create index ix_fundamental_snapshot_query_code on dsa.fundamental_snapshot (query_id, code);
create index ix_fundamental_snapshot_query_id on dsa.fundamental_snapshot (query_id);

create table dsa.intelligence_sources (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  source_type varchar(32) not null default 'rss',
  url varchar(1000) not null,
  enabled boolean not null default true,
  scope_type varchar(32) not null default 'market',
  scope_value varchar(64),
  market varchar(32) not null default 'vn',
  description text,
  last_status varchar(32),
  last_error text,
  last_fetched_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index ix_intel_source_scope on dsa.intelligence_sources (scope_type, scope_value, market);
create index ix_intelligence_sources_created_at on dsa.intelligence_sources (created_at);
create index ix_intelligence_sources_enabled on dsa.intelligence_sources (enabled);
create index ix_intelligence_sources_last_fetched_at on dsa.intelligence_sources (last_fetched_at);
create index ix_intelligence_sources_market on dsa.intelligence_sources (market);
create unique index ix_intelligence_sources_name on dsa.intelligence_sources (name);
create index ix_intelligence_sources_scope_type on dsa.intelligence_sources (scope_type);
create index ix_intelligence_sources_scope_value on dsa.intelligence_sources (scope_value);
create index ix_intelligence_sources_source_type on dsa.intelligence_sources (source_type);
create index ix_intelligence_sources_updated_at on dsa.intelligence_sources (updated_at);

create table dsa.llm_usage (
  id bigint generated by default as identity primary key,
  call_type varchar(32) not null,
  model varchar(128) not null,
  stock_code varchar(16),
  provider varchar(64),
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  total_tokens integer not null default 0,
  provider_usage_json jsonb,
  provider_usage_schema_name varchar(64),
  provider_usage_schema_version varchar(32),
  provider_usage_observed_at varchar(32),
  normalized_prompt_tokens integer,
  normalized_completion_tokens integer,
  normalized_total_tokens integer,
  normalized_cache_read_tokens integer,
  normalized_cache_write_tokens integer,
  normalized_cache_miss_tokens integer,
  normalized_uncached_input_tokens integer,
  normalized_cache_eligible_input_tokens integer,
  normalized_cache_hit_ratio double precision,
  normalized_cache_write_ratio double precision,
  cache_capability varchar(32),
  cache_eligibility varchar(32),
  cache_observation varchar(32),
  estimated_prefix_tokens integer,
  provider_reported_prompt_tokens integer,
  provider_reported_cached_tokens integer,
  provider_min_cache_tokens integer,
  eligibility_confidence varchar(32),
  tokenizer_name varchar(128),
  tokenizer_version varchar(64),
  messages_hmac varchar(64),
  system_message_hmac varchar(64),
  user_message_hmac varchar(64),
  hmac_key_version varchar(64),
  hmac_domain varchar(32),
  hash_scope varchar(32),
  language varchar(16),
  market_group varchar(16),
  analysis_mode varchar(64),
  legacy_prompt_mode varchar(32),
  skill_config_hmac varchar(64),
  transport varchar(64),
  message_count integer,
  estimated_total_prompt_tokens integer,
  approx_common_prefix_chars integer,
  approx_common_prefix_tokens integer,
  known_dynamic_marker_positions jsonb,
  called_at timestamptz default now(),
  constraint ck_llm_usage_stock_code_vn check (stock_code is null or stock_code ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_llm_usage_prompt_tokens_nonnegative check (prompt_tokens >= 0),
  constraint ck_llm_usage_completion_tokens_nonnegative check (completion_tokens >= 0),
  constraint ck_llm_usage_total_tokens_nonnegative check (total_tokens >= 0),
  constraint ck_llm_usage_normalized_prompt_tokens_nonnegative check (normalized_prompt_tokens is null or normalized_prompt_tokens >= 0),
  constraint ck_llm_usage_normalized_completion_tokens_nonnegative check (normalized_completion_tokens is null or normalized_completion_tokens >= 0),
  constraint ck_llm_usage_normalized_total_tokens_nonnegative check (normalized_total_tokens is null or normalized_total_tokens >= 0),
  constraint ck_llm_usage_normalized_cache_read_tokens_nonnegative check (normalized_cache_read_tokens is null or normalized_cache_read_tokens >= 0),
  constraint ck_llm_usage_normalized_cache_write_tokens_nonnegative check (normalized_cache_write_tokens is null or normalized_cache_write_tokens >= 0),
  constraint ck_llm_usage_normalized_cache_miss_tokens_nonnegative check (normalized_cache_miss_tokens is null or normalized_cache_miss_tokens >= 0),
  constraint ck_llm_usage_normalized_uncached_input_tokens_nonnegative check (normalized_uncached_input_tokens is null or normalized_uncached_input_tokens >= 0),
  constraint ck_llm_usage_normalized_cache_eligible_input_tokens_nonnegative check (normalized_cache_eligible_input_tokens is null or normalized_cache_eligible_input_tokens >= 0),
  constraint ck_llm_usage_estimated_prefix_tokens_nonnegative check (estimated_prefix_tokens is null or estimated_prefix_tokens >= 0),
  constraint ck_llm_usage_provider_reported_prompt_tokens_nonnegative check (provider_reported_prompt_tokens is null or provider_reported_prompt_tokens >= 0),
  constraint ck_llm_usage_provider_reported_cached_tokens_nonnegative check (provider_reported_cached_tokens is null or provider_reported_cached_tokens >= 0),
  constraint ck_llm_usage_provider_min_cache_tokens_nonnegative check (provider_min_cache_tokens is null or provider_min_cache_tokens >= 0),
  constraint ck_llm_usage_message_count_nonnegative check (message_count is null or message_count >= 0),
  constraint ck_llm_usage_estimated_total_prompt_tokens_nonnegative check (estimated_total_prompt_tokens is null or estimated_total_prompt_tokens >= 0),
  constraint ck_llm_usage_approx_common_prefix_tokens_nonnegative check (approx_common_prefix_tokens is null or approx_common_prefix_tokens >= 0)
);

create index ix_llm_usage_call_type on dsa.llm_usage (call_type);
create index ix_llm_usage_called_at on dsa.llm_usage (called_at);

create table dsa.news_intel (
  id bigint generated by default as identity primary key,
  query_id varchar(64),
  code varchar(10) not null,
  name varchar(50),
  dimension varchar(32),
  query varchar(255),
  provider varchar(32),
  title varchar(300) not null,
  snippet text,
  url varchar(1000) not null,
  source varchar(100),
  published_date timestamptz,
  fetched_at timestamptz default now(),
  query_source varchar(32),
  requester_platform varchar(20),
  requester_user_id varchar(64),
  requester_user_name varchar(64),
  requester_chat_id varchar(64),
  requester_message_id varchar(64),
  requester_query varchar(255),
  constraint uix_news_url unique (url),
  constraint ck_news_intel_code_vn check (code ~ '^[A-Z0-9]{1,12}[.]VN$')
);

create index ix_news_code_pub on dsa.news_intel (code, published_date);
create index ix_news_intel_code on dsa.news_intel (code);
create index ix_news_intel_dimension on dsa.news_intel (dimension);
create index ix_news_intel_fetched_at on dsa.news_intel (fetched_at);
create index ix_news_intel_provider on dsa.news_intel (provider);
create index ix_news_intel_published_date on dsa.news_intel (published_date);
create index ix_news_intel_query_id on dsa.news_intel (query_id);
create index ix_news_intel_query_source on dsa.news_intel (query_source);

create table dsa.portfolio_accounts (
  id bigint generated by default as identity primary key,
  owner_id varchar(64),
  name varchar(64) not null,
  broker varchar(64),
  market varchar(8) not null default 'vn',
  base_currency varchar(8) not null default 'VND',
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint ck_portfolio_accounts_base_currency_vnd check (base_currency = 'VND')
);

create index ix_portfolio_account_owner_active on dsa.portfolio_accounts (owner_id, is_active);
create index ix_portfolio_accounts_created_at on dsa.portfolio_accounts (created_at);
create index ix_portfolio_accounts_is_active on dsa.portfolio_accounts (is_active);
create index ix_portfolio_accounts_market on dsa.portfolio_accounts (market);
create index ix_portfolio_accounts_owner_id on dsa.portfolio_accounts (owner_id);

create table dsa.portfolio_fx_rates (
  id bigint generated by default as identity primary key,
  from_currency varchar(8) not null,
  to_currency varchar(8) not null,
  rate_date date not null,
  rate double precision not null,
  source varchar(32) not null default 'manual',
  is_stale boolean not null default false,
  updated_at timestamptz default now(),
  constraint uix_portfolio_fx_pair_date unique (from_currency, to_currency, rate_date),
  constraint ck_portfolio_fx_rates_from_currency_vnd check (from_currency = 'VND'),
  constraint ck_portfolio_fx_rates_to_currency_vnd check (to_currency = 'VND')
);

create index ix_portfolio_fx_rates_from_currency on dsa.portfolio_fx_rates (from_currency);
create index ix_portfolio_fx_rates_rate_date on dsa.portfolio_fx_rates (rate_date);
create index ix_portfolio_fx_rates_to_currency on dsa.portfolio_fx_rates (to_currency);

create table dsa.stock_daily (
  id bigint generated by default as identity primary key,
  code varchar(10) not null,
  date date not null,
  open double precision,
  high double precision,
  low double precision,
  close double precision,
  volume double precision,
  amount double precision,
  pct_chg double precision,
  ma5 double precision,
  ma10 double precision,
  ma20 double precision,
  volume_ratio double precision,
  data_source varchar(50),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint uix_code_date unique (code, date),
  constraint ck_stock_daily_code_vn check (code ~ '^[A-Z0-9]{1,12}[.]VN$')
);

create index ix_code_date on dsa.stock_daily (code, date);
create index ix_stock_daily_code on dsa.stock_daily (code);
create index ix_stock_daily_date on dsa.stock_daily (date);

create table dsa.backtest_results (
  id bigint generated by default as identity primary key,
  analysis_history_id bigint not null references dsa.analysis_history(id),
  code varchar(10) not null,
  analysis_date date,
  eval_window_days integer not null default 10,
  engine_version varchar(16) not null default 'v1',
  eval_status varchar(16) not null default 'pending',
  evaluated_at timestamptz default now(),
  operation_advice varchar(20),
  position_recommendation varchar(8),
  start_price double precision,
  end_close double precision,
  max_high double precision,
  min_low double precision,
  stock_return_pct double precision,
  direction_expected varchar(16),
  direction_correct boolean,
  outcome varchar(16),
  stop_loss double precision,
  take_profit double precision,
  hit_stop_loss boolean,
  hit_take_profit boolean,
  first_hit varchar(16),
  first_hit_date date,
  first_hit_trading_days integer,
  simulated_entry_price double precision,
  simulated_exit_price double precision,
  simulated_exit_reason varchar(24),
  simulated_return_pct double precision,
  constraint uix_backtest_analysis_window_version unique (analysis_history_id, eval_window_days, engine_version),
  constraint ck_backtest_results_code_vn check (code ~ '^[A-Z0-9]{1,12}[.]VN$')
);

create index ix_backtest_code_date on dsa.backtest_results (code, analysis_date);
create index ix_backtest_results_analysis_date on dsa.backtest_results (analysis_date);
create index ix_backtest_results_analysis_history_id on dsa.backtest_results (analysis_history_id);
create index ix_backtest_results_code on dsa.backtest_results (code);
create index ix_backtest_results_evaluated_at on dsa.backtest_results (evaluated_at);

create table dsa.intelligence_items (
  id bigint generated by default as identity primary key,
  source_id bigint references dsa.intelligence_sources(id) on delete set null,
  source_name varchar(100),
  source_type varchar(32) not null default 'rss',
  title varchar(300) not null,
  summary text,
  url varchar(1000) not null,
  source varchar(100),
  published_at timestamptz,
  fetched_at timestamptz default now(),
  scope_type varchar(32) not null default 'market',
  scope_value varchar(64) not null default '__dsa_null_scope__',
  market varchar(32) not null default 'vn',
  raw_payload jsonb,
  constraint uix_intel_item_source_scope_url unique (source_id, url, scope_type, scope_value, market)
);

create index ix_intel_item_fetch_time on dsa.intelligence_items (fetched_at);
create index ix_intel_item_scope_time on dsa.intelligence_items (scope_type, scope_value, market, published_at);
create index ix_intelligence_items_fetched_at on dsa.intelligence_items (fetched_at);
create index ix_intelligence_items_market on dsa.intelligence_items (market);
create index ix_intelligence_items_published_at on dsa.intelligence_items (published_at);
create index ix_intelligence_items_scope_type on dsa.intelligence_items (scope_type);
create index ix_intelligence_items_scope_value on dsa.intelligence_items (scope_value);
create index ix_intelligence_items_source_id on dsa.intelligence_items (source_id);
create index ix_intelligence_items_source_name on dsa.intelligence_items (source_name);
create index ix_intelligence_items_source_type on dsa.intelligence_items (source_type);
create index ix_intelligence_items_url on dsa.intelligence_items (url);

create table dsa.portfolio_cash_ledger (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id),
  event_date date not null,
  direction varchar(8) not null,
  amount double precision not null,
  currency varchar(8) not null default 'VND',
  note varchar(255),
  created_at timestamptz default now(),
  constraint ck_portfolio_cash_ledger_currency_vnd check (currency = 'VND')
);

create index ix_portfolio_cash_account_date on dsa.portfolio_cash_ledger (account_id, event_date);
create index ix_portfolio_cash_ledger_account_id on dsa.portfolio_cash_ledger (account_id);
create index ix_portfolio_cash_ledger_created_at on dsa.portfolio_cash_ledger (created_at);
create index ix_portfolio_cash_ledger_event_date on dsa.portfolio_cash_ledger (event_date);

create table dsa.portfolio_corporate_actions (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id),
  symbol varchar(16) not null,
  market varchar(8) not null default 'vn',
  currency varchar(8) not null default 'VND',
  effective_date date not null,
  action_type varchar(24) not null,
  cash_dividend_per_share double precision,
  split_ratio double precision,
  note varchar(255),
  created_at timestamptz default now(),
  constraint ck_portfolio_corporate_actions_symbol_vn check (symbol ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_portfolio_corporate_actions_currency_vnd check (currency = 'VND')
);

create index ix_portfolio_ca_account_date on dsa.portfolio_corporate_actions (account_id, effective_date);
create index ix_portfolio_corporate_actions_account_id on dsa.portfolio_corporate_actions (account_id);
create index ix_portfolio_corporate_actions_created_at on dsa.portfolio_corporate_actions (created_at);
create index ix_portfolio_corporate_actions_effective_date on dsa.portfolio_corporate_actions (effective_date);
create index ix_portfolio_corporate_actions_symbol on dsa.portfolio_corporate_actions (symbol);

create table dsa.portfolio_daily_snapshots (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id),
  snapshot_date date not null,
  cost_method varchar(8) not null default 'fifo',
  base_currency varchar(8) not null default 'VND',
  total_cash double precision not null default 0.0,
  total_market_value double precision not null default 0.0,
  total_equity double precision not null default 0.0,
  unrealized_pnl double precision not null default 0.0,
  realized_pnl double precision not null default 0.0,
  fee_total double precision not null default 0.0,
  tax_total double precision not null default 0.0,
  fx_stale boolean not null default false,
  payload jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint uix_portfolio_snapshot_account_date_method unique (account_id, snapshot_date, cost_method),
  constraint ck_portfolio_daily_snapshots_base_currency_vnd check (base_currency = 'VND')
);

create index ix_portfolio_daily_snapshots_account_id on dsa.portfolio_daily_snapshots (account_id);
create index ix_portfolio_daily_snapshots_created_at on dsa.portfolio_daily_snapshots (created_at);
create index ix_portfolio_daily_snapshots_snapshot_date on dsa.portfolio_daily_snapshots (snapshot_date);

create table dsa.portfolio_positions (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id),
  cost_method varchar(8) not null default 'fifo',
  symbol varchar(16) not null,
  market varchar(8) not null default 'vn',
  currency varchar(8) not null default 'VND',
  quantity double precision not null default 0.0,
  avg_cost double precision not null default 0.0,
  total_cost double precision not null default 0.0,
  last_price double precision not null default 0.0,
  market_value_base double precision not null default 0.0,
  unrealized_pnl_base double precision not null default 0.0,
  valuation_currency varchar(8) not null default 'VND',
  position_lifecycle varchar(16) not null default 'open',
  settlement_state varchar(24) not null default 'unknown',
  sellable_quantity double precision not null default 0.0,
  unsettled_quantity double precision not null default 0.0,
  next_sellable_at timestamptz,
  settlement_calculation_status varchar(16) not null default 'unknown',
  updated_at timestamptz default now(),
  constraint uix_portfolio_position_account_symbol_market_currency unique (account_id, symbol, market, currency, cost_method),
  constraint ck_portfolio_positions_symbol_vn check (symbol ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_portfolio_positions_currency_vnd check (currency = 'VND'),
  constraint ck_portfolio_positions_quantity_nonnegative check (quantity >= 0),
  constraint ck_portfolio_positions_valuation_currency_vnd check (valuation_currency = 'VND'),
  constraint ck_portfolio_positions_sellable_quantity_nonnegative check (sellable_quantity >= 0),
  constraint ck_portfolio_positions_unsettled_quantity_nonnegative check (unsettled_quantity >= 0)
);

create index ix_portfolio_positions_account_id on dsa.portfolio_positions (account_id);
create index ix_portfolio_positions_symbol on dsa.portfolio_positions (symbol);
create index ix_portfolio_positions_updated_at on dsa.portfolio_positions (updated_at);

create table dsa.portfolio_trades (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id),
  trade_uid varchar(128),
  symbol varchar(16) not null,
  market varchar(8) not null default 'vn',
  currency varchar(8) not null default 'VND',
  trade_date date not null,
  executed_at timestamptz,
  side varchar(8) not null,
  quantity double precision not null,
  price double precision not null,
  fee double precision default 0.0,
  tax double precision default 0.0,
  note varchar(255),
  dedup_hash varchar(64),
  created_at timestamptz default now(),
  constraint uix_portfolio_trade_dedup_hash unique (account_id, dedup_hash),
  constraint uix_portfolio_trade_uid unique (account_id, trade_uid),
  constraint ck_portfolio_trades_symbol_vn check (symbol ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_portfolio_trades_currency_vnd check (currency = 'VND'),
  constraint ck_portfolio_trades_quantity_nonnegative check (quantity >= 0)
);

create index ix_portfolio_trade_account_date on dsa.portfolio_trades (account_id, trade_date);
create index ix_portfolio_trades_account_id on dsa.portfolio_trades (account_id);
create index ix_portfolio_trades_created_at on dsa.portfolio_trades (created_at);
create index ix_portfolio_trades_dedup_hash on dsa.portfolio_trades (dedup_hash);
create index ix_portfolio_trades_symbol on dsa.portfolio_trades (symbol);
create index ix_portfolio_trades_trade_date on dsa.portfolio_trades (trade_date);

create table dsa.settlement_alert_states (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id) on delete cascade,
  symbol varchar(16) not null,
  market varchar(8) not null default 'vn',
  settlement_state varchar(24) not null default 'unknown',
  total_quantity double precision not null default 0.0,
  sellable_quantity double precision not null default 0.0,
  unsettled_quantity double precision not null default 0.0,
  thesis_invalidated boolean not null default false,
  source_signal_id integer,
  risk_level varchar(16),
  risk_rank integer,
  risk_policy_version varchar(64),
  observed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uix_settlement_alert_state_account_symbol unique (account_id, symbol),
  constraint ck_settlement_alert_states_symbol_vn check (symbol ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_settlement_alert_states_total_quantity_nonnegative check (total_quantity >= 0),
  constraint ck_settlement_alert_states_sellable_quantity_nonnegative check (sellable_quantity >= 0),
  constraint ck_settlement_alert_states_unsettled_quantity_nonnegative check (unsettled_quantity >= 0)
);

create index ix_settlement_alert_states_account_id on dsa.settlement_alert_states (account_id);
create index ix_settlement_alert_states_market on dsa.settlement_alert_states (market);
create index ix_settlement_alert_states_observed_at on dsa.settlement_alert_states (observed_at);
create index ix_settlement_alert_states_source_signal_id on dsa.settlement_alert_states (source_signal_id);
create index ix_settlement_alert_states_symbol on dsa.settlement_alert_states (symbol);
create index ix_settlement_alert_states_updated_at on dsa.settlement_alert_states (updated_at);

create table dsa.decision_signal_trade_links (
  id bigint generated by default as identity primary key,
  signal_id bigint not null references dsa.decision_signals(id) on delete cascade,
  trade_id bigint not null references dsa.portfolio_trades(id) on delete cascade,
  link_type varchar(32) not null default 'source_recommendation',
  created_at timestamptz not null default now(),
  constraint uix_decision_signal_trade_link unique (signal_id, trade_id, link_type),
  constraint uix_trade_source_recommendation_link unique (trade_id, link_type)
);

create index ix_decision_signal_trade_links_created_at on dsa.decision_signal_trade_links (created_at);
create index ix_decision_signal_trade_links_link_type on dsa.decision_signal_trade_links (link_type);
create index ix_decision_signal_trade_links_signal_id on dsa.decision_signal_trade_links (signal_id);
create index ix_decision_signal_trade_links_trade_id on dsa.decision_signal_trade_links (trade_id);

create table dsa.portfolio_position_lots (
  id bigint generated by default as identity primary key,
  account_id bigint not null references dsa.portfolio_accounts(id),
  cost_method varchar(8) not null default 'fifo',
  symbol varchar(16) not null,
  market varchar(8) not null default 'vn',
  currency varchar(8) not null default 'VND',
  open_date date not null,
  remaining_quantity double precision not null default 0.0,
  unit_cost double precision not null default 0.0,
  source_trade_id bigint references dsa.portfolio_trades(id),
  estimated_sellable_at timestamptz,
  actual_sellable_at timestamptz,
  settlement_state varchar(24) not null default 'unknown',
  calendar_status varchar(16) not null default 'unknown',
  updated_at timestamptz default now(),
  constraint ck_portfolio_position_lots_symbol_vn check (symbol ~ '^[A-Z0-9]{1,12}[.]VN$'),
  constraint ck_portfolio_position_lots_currency_vnd check (currency = 'VND'),
  constraint ck_portfolio_position_lots_remaining_quantity_nonnegative check (remaining_quantity >= 0)
);

create index ix_portfolio_lot_account_symbol on dsa.portfolio_position_lots (account_id, symbol);
create index ix_portfolio_position_lots_account_id on dsa.portfolio_position_lots (account_id);
create index ix_portfolio_position_lots_open_date on dsa.portfolio_position_lots (open_date);
create index ix_portfolio_position_lots_symbol on dsa.portfolio_position_lots (symbol);
create index ix_portfolio_position_lots_updated_at on dsa.portfolio_position_lots (updated_at);

create table dsa.portfolio_trade_settlements (
  trade_id bigint primary key references dsa.portfolio_trades(id) on delete cascade,
  settlement_date date not null,
  estimated_sellable_at timestamptz not null,
  actual_sellable_at timestamptz,
  calendar_version varchar(255) not null,
  policy_version varchar(64) not null,
  calculation_status varchar(16) not null,
  warnings_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index ix_portfolio_trade_settlements_actual_sellable_at on dsa.portfolio_trade_settlements (actual_sellable_at);
create index ix_portfolio_trade_settlements_calculation_status on dsa.portfolio_trade_settlements (calculation_status);
create index ix_portfolio_trade_settlements_created_at on dsa.portfolio_trade_settlements (created_at);
create index ix_portfolio_trade_settlements_estimated_sellable_at on dsa.portfolio_trade_settlements (estimated_sellable_at);
create index ix_portfolio_trade_settlements_settlement_date on dsa.portfolio_trade_settlements (settlement_date);

create table dsa.settlement_outcomes (
  id bigint generated by default as identity primary key,
  signal_id bigint not null references dsa.decision_signals(id) on delete cascade,
  source_trade_id bigint references dsa.portfolio_trades(id) on delete cascade,
  outcome_type varchar(16) not null,
  record_key varchar(64) not null,
  engine_version varchar(64) not null,
  entry_policy_version varchar(64) not null,
  calendar_version varchar(255),
  settlement_policy_version varchar(64),
  anchor_date date,
  estimated_settlement_date date,
  estimated_first_sellable_at timestamptz,
  entry_price double precision,
  return_t1_pct double precision,
  return_t2_pct double precision,
  return_first_sellable_pct double precision,
  return_t5_pct double precision,
  return_t10_pct double precision,
  return_t20_pct double precision,
  mae_before_sellable_pct double precision,
  mfe_before_sellable_pct double precision,
  invalidation_before_sellable boolean,
  operationally_executable boolean not null default false,
  estimated_fee_pct double precision,
  estimated_slippage_pct double precision,
  net_return_first_sellable_pct double precision,
  data_quality varchar(24) not null default 'unknown',
  unavailable_reason varchar(64),
  ambiguity_flags_json jsonb not null default '[]'::jsonb,
  settlement_risk_score double precision,
  survivability_bucket varchar(24),
  liquidity_bucket varchar(24),
  guarded_action varchar(16),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uix_settlement_outcome_versioned_key unique (signal_id, outcome_type, record_key, engine_version, entry_policy_version)
);

create index ix_settlement_outcome_stats on dsa.settlement_outcomes (engine_version, outcome_type, guarded_action);
create index ix_settlement_outcomes_anchor_date on dsa.settlement_outcomes (anchor_date);
create index ix_settlement_outcomes_created_at on dsa.settlement_outcomes (created_at);
create index ix_settlement_outcomes_data_quality on dsa.settlement_outcomes (data_quality);
create index ix_settlement_outcomes_engine_version on dsa.settlement_outcomes (engine_version);
create index ix_settlement_outcomes_entry_policy_version on dsa.settlement_outcomes (entry_policy_version);
create index ix_settlement_outcomes_estimated_first_sellable_at on dsa.settlement_outcomes (estimated_first_sellable_at);
create index ix_settlement_outcomes_estimated_settlement_date on dsa.settlement_outcomes (estimated_settlement_date);
create index ix_settlement_outcomes_guarded_action on dsa.settlement_outcomes (guarded_action);
create index ix_settlement_outcomes_liquidity_bucket on dsa.settlement_outcomes (liquidity_bucket);
create index ix_settlement_outcomes_outcome_type on dsa.settlement_outcomes (outcome_type);
create index ix_settlement_outcomes_signal_id on dsa.settlement_outcomes (signal_id);
create index ix_settlement_outcomes_source_trade_id on dsa.settlement_outcomes (source_trade_id);
create index ix_settlement_outcomes_survivability_bucket on dsa.settlement_outcomes (survivability_bucket);
create index ix_settlement_outcomes_unavailable_reason on dsa.settlement_outcomes (unavailable_reason);
create index ix_settlement_outcomes_updated_at on dsa.settlement_outcomes (updated_at);

revoke all on all tables in schema dsa from public, anon, authenticated, service_role;
revoke all on all sequences in schema dsa from public, anon, authenticated, service_role;
grant usage on schema dsa to dsa_worker;
grant select, insert, update, delete on all tables in schema dsa to dsa_worker;
grant usage, select on all sequences in schema dsa to dsa_worker;

alter default privileges in schema dsa revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema dsa revoke all on sequences from public, anon, authenticated, service_role;
alter default privileges in schema dsa grant select, insert, update, delete on tables to dsa_worker;
alter default privileges in schema dsa grant usage, select on sequences to dsa_worker;

alter table dsa.agent_provider_turns enable row level security;
create policy agent_provider_turns_worker_all on dsa.agent_provider_turns
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.alert_cooldowns enable row level security;
create policy alert_cooldowns_worker_all on dsa.alert_cooldowns
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.alert_notifications enable row level security;
create policy alert_notifications_worker_all on dsa.alert_notifications
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.alert_rules enable row level security;
create policy alert_rules_worker_all on dsa.alert_rules
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.alert_triggers enable row level security;
create policy alert_triggers_worker_all on dsa.alert_triggers
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.analysis_history enable row level security;
create policy analysis_history_worker_all on dsa.analysis_history
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.backtest_results enable row level security;
create policy backtest_results_worker_all on dsa.backtest_results
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.backtest_summaries enable row level security;
create policy backtest_summaries_worker_all on dsa.backtest_summaries
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.conversation_messages enable row level security;
create policy conversation_messages_worker_all on dsa.conversation_messages
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.conversation_summaries enable row level security;
create policy conversation_summaries_worker_all on dsa.conversation_summaries
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.decision_signal_feedback enable row level security;
create policy decision_signal_feedback_worker_all on dsa.decision_signal_feedback
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.decision_signal_outcomes enable row level security;
create policy decision_signal_outcomes_worker_all on dsa.decision_signal_outcomes
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.decision_signal_trade_links enable row level security;
create policy decision_signal_trade_links_worker_all on dsa.decision_signal_trade_links
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.decision_signals enable row level security;
create policy decision_signals_worker_all on dsa.decision_signals
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.fundamental_snapshot enable row level security;
create policy fundamental_snapshot_worker_all on dsa.fundamental_snapshot
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.intelligence_items enable row level security;
create policy intelligence_items_worker_all on dsa.intelligence_items
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.intelligence_sources enable row level security;
create policy intelligence_sources_worker_all on dsa.intelligence_sources
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.llm_usage enable row level security;
create policy llm_usage_worker_all on dsa.llm_usage
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.news_intel enable row level security;
create policy news_intel_worker_all on dsa.news_intel
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_accounts enable row level security;
create policy portfolio_accounts_worker_all on dsa.portfolio_accounts
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_cash_ledger enable row level security;
create policy portfolio_cash_ledger_worker_all on dsa.portfolio_cash_ledger
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_corporate_actions enable row level security;
create policy portfolio_corporate_actions_worker_all on dsa.portfolio_corporate_actions
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_daily_snapshots enable row level security;
create policy portfolio_daily_snapshots_worker_all on dsa.portfolio_daily_snapshots
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_fx_rates enable row level security;
create policy portfolio_fx_rates_worker_all on dsa.portfolio_fx_rates
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_position_lots enable row level security;
create policy portfolio_position_lots_worker_all on dsa.portfolio_position_lots
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_positions enable row level security;
create policy portfolio_positions_worker_all on dsa.portfolio_positions
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_trade_settlements enable row level security;
create policy portfolio_trade_settlements_worker_all on dsa.portfolio_trade_settlements
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.portfolio_trades enable row level security;
create policy portfolio_trades_worker_all on dsa.portfolio_trades
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.settlement_alert_states enable row level security;
create policy settlement_alert_states_worker_all on dsa.settlement_alert_states
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.settlement_outcomes enable row level security;
create policy settlement_outcomes_worker_all on dsa.settlement_outcomes
  for all
  to dsa_worker
  using (true)
  with check (true);

alter table dsa.stock_daily enable row level security;
create policy stock_daily_worker_all on dsa.stock_daily
  for all
  to dsa_worker
  using (true)
  with check (true);
